from tkinter import *
root=Tk()
root.geometry('350x200')
root.title("surajit")
def myfun():
    print(" hii i am surajit mandal")
## normal menu
# mymenu=Menu(root)
# mymenu.add_command(label='file', command=myfun)
# mymenu.add_command(label='exit',command=quit)
# root.config(menu=mymenu)
mainmenu=Menu(root)
m1=Menu(mainmenu,tearoff=0)
m1.add_command(label="save",command=myfun)
m1.add_separator()
m1.add_command(label="new folder",command=myfun)
m1.add_separator()
m1.add_command(label="delete",command=myfun)
root.config(menu=mainmenu)
mainmenu.add_cascade(label='file',menu=m1)
m2=Menu(mainmenu,tearoff=0)
m2.add_command(label="save1",command=myfun)
m2.add_command(label="new folder1",command=myfun)
m2.add_command(label="delete1",command=myfun)
root.config(menu=mainmenu)
mainmenu.add_cascade(label='edit',menu=m1)
mainmenu.add_command(label='EXIT', command=quit)

### enter point
leb=Label(root, text='are you geek?')
leb.grid()
txt=Entry(root, width=10)
txt.grid(column=1,row=0)
def clicked():
    res="you are wrote" + txt.get()
    leb.config(text = res)
btn=Button(root, text='click me', command=clicked)
btn.grid(column=2,row=0)
root.mainloop()